# Generated by Django 2.2.13 on 2021-03-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingcode',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trackingcode',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingcode',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
