version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Activate venv and Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
          asas:
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            make migrations
            make migrate
          name: Run Migrations
      - run:
          command: |
            . venv/bin/activate
            make test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test:
          context: default-context
