# Generated by Django 3.2 on 2021-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210310_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tracking_event',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='TrackingCode',
        ),
    ]
