# Generated by Django 3.2 on 2021-05-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20210514_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackingEvent',
            new_name='TrackingEventModel',
        ),
    ]
